from .contact_us import *
from .footer import *
from .gallery import *
from .menu import *
from .notice_board import *
from .madrasah_figure import *
from .summary_slider import *
from .support_for_madrasah import *
from .teacher import *
from .wallpaper import *